services:
  - type: web
    name: jobpilot-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://jobpilot-livid-omega.vercel.app
      - key: FRONTEND_URL
        value: https://jobpilot-livid-omega.vercel.app
      - key: VITE_CLIENT_URL
        value: https://jobpilot-livid-omega.vercel.app
      - key: CORS_ORIGIN
        value: https://jobpilot-livid-omega.vercel.app
