/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#0b0c0c',
        foreground: '#f7f1ef',
        primary: '#b64f52',
        'primary-dark': '#9e4145',
        secondary: '#1b1b1b',
        tertiary: '#262322',
        accent: '#49d7ca',
        border: '#342928',
        muted: '#a79390',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Menlo', 'monospace'],
      },
      fontSize: {
        'xs': ['clamp(0.75rem, 1vw, 0.875rem)', { lineHeight: '1.25rem' }],
        'sm': ['clamp(0.875rem, 1.2vw, 1rem)', { lineHeight: '1.5rem' }],
        'base': ['clamp(1rem, 1.4vw, 1.125rem)', { lineHeight: '1.75rem' }],
        'lg': ['clamp(1.125rem, 1.6vw, 1.25rem)', { lineHeight: '1.875rem' }],
        'xl': ['clamp(1.25rem, 2vw, 1.5rem)', { lineHeight: '2rem' }],
        '2xl': ['clamp(1.5rem, 2.5vw, 1.875rem)', { lineHeight: '2.25rem' }],
        '3xl': ['clamp(1.875rem, 3vw, 2.25rem)', { lineHeight: '2.5rem' }],
        '4xl': ['clamp(2.25rem, 4vw, 3rem)', { lineHeight: '3.5rem' }],
        '5xl': ['clamp(3rem, 5vw, 3.75rem)', { lineHeight: '4.5rem' }],
      },
      spacing: {
        'xs': 'clamp(0.5rem, 2vw, 1rem)',
        'sm': 'clamp(0.75rem, 3vw, 1.5rem)',
        'md': 'clamp(1rem, 4vw, 2rem)',
        'lg': 'clamp(1.5rem, 5vw, 3rem)',
        'xl': 'clamp(2rem, 6vw, 4rem)',
      },
      borderRadius: {
        'xs': '0.25rem',
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
      },
      screens: {
        'xs': '320px',
        'sm': '480px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        'container': '100%',
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
    },
  },
  plugins: [],
}

